version: '3'

services:
    fuseki:
        container_name: fuseki
        image: stain/jena-fuseki:4.0.0
        restart: always
        ports:
            # host:container
            - 3030:3030
        env_file:
            - fuseki.env
        volumes:
            - type: bind
              source: ./data
              target: /fuseki

